services:
  db:
    image: postgres:16
    container_name: imageflow_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
    networks:
      - imageflow-network

  redis:
    image: redis:latest
    container_name: imageflow_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - imageflow-network

  backend: &backend
    build: ./services/backend
    command: python manage.py runapplication
    container_name: imageflow_backend
    volumes:
      - ./services/backend:/app
    env_file:
      - ./env/backend.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - imageflow-network

  celeryworker:
    <<: *backend
    command: python manage.py runapplication --celery
    container_name: imageflow_celery_worker
    depends_on:
      - backend
      - db
      - redis
    ports:
      - "8001:8001"

volumes:
  postgres_data:
    driver: local
    name: imageflow_backend_data

networks:
  imageflow-network:
    driver: bridge